version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  redis:
    image: redis:7.0-alpine
    ports:
      - '6379'

  monitor:
    build:
      context: ../app
      dockerfile: Dockerfile
    volumes:
      - "./app:/code"
    ports:
      - "2112:2112"
    depends_on:
      - redis
      - flask

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - '../prometheus/:/etc/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - monitor
      - flask
    restart: always

  grafana:
    image: grafana/grafana-enterprise:latest
    user: "1000"
    volumes:
      - '../grafana/:/var/lib/grafana:z'
    ports:
      - '3030:3000'
    depends_on:
      - prometheus
    restart: always

