interval = 120
port = 2112

[statuspage]
    apikey = "apikey_teste"
    pageid = "pageid_teste"

[discord]
    role_id = "role_id_teste"
    id = "identificador_teste"
    token = "token_teste"

[redis]
    host = '172.24.29.107'
    port = 6379

[[modules]]
    name = "teste_numero_1"
    statuspage_id = "sp_id_teste"
    notify = ["123", "456"]
    [[modules.test]]
        type = "http"
        url = "https://google.com"
        method = "get"

[[modules]]
    name = "teste_numero_2"
    statuspage_id = "sp_id_teste"
    notify = ["123", "456"]
    [[modules.test]]
        type = "http"
        url = "https://quempuc.biobd.inf.puc-rio.br"
        method = "get"
