version: "3"

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379'

  monitor:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "2112:2112"
    depends_on:
      - redis
    # extra_hosts:
    #   - "intercambio.biobd.inf.puc-rio.br:10.0.0.15"
    #   - "neam.biobd.inf.puc-rio.br:10.0.2.10"
    #   - "etc.biobd.inf.puc-rio.br:10.0.2.11"
    #   - "buscanima.biobd.inf.puc-rio.br:10.0.2.12"
    #   - "enem.biobd.inf.puc-rio.br:10.0.2.13"
    #   - "quemnapuc.biobd.inf.puc-rio.br:10.0.2.12"
    #   - "quempuc.biobd.inf.puc-rio.br:10.0.2.12"
    #   - "biobd.inf.puc-rio.br:10.0.2.28"
    #   - "donare.biobd.inf.puc-rio.br:10.0.2.23"
    #   - "elo.donare.biobd.inf.puc-rio.br:10.0.2.23"
    #   - "solid.biobd.inf.puc-rio.br:10.0.2.22"
    #   - "handson.biobd.inf.puc-rio.br:10.0.2.31"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - monitor
    restart: always

  grafana:
    image: grafana/grafana-enterprise:latest
    user: "1000"
    volumes:
      - './grafana/:/var/lib/grafana:z'
    ports:
      - '3030:3000'
    depends_on:
      - prometheus
    restart: always

