version: "3"

services:
  redis:
    image: redis:7.0-alpine
    ports:
      - '6379'

  monitor:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "2112:2112"
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - monitor
    restart: always

  grafana:
    image: grafana/grafana-enterprise:latest
    user: "1000"
    volumes:
      - './grafana/:/var/lib/grafana:z'
    ports:
      - '3030:3000'
    depends_on:
      - prometheus
    restart: always

