global:
  scrape_interval: 1m
  scrape_timeout: 30s

  external_labels:
    monitor: 'monitoramento'

scrape_configs:
  - job_name: 'monitor'
    static_configs:
      - targets: ['monitor:2112']   # ip do monitor é "monitor" devido ao uso com docker